## QUICK CREDIT v0.4

## Python Script to add header to a batch of JAVA source code files 
##  This is tool is made by Aharnish Pithva for anyone to use and modify for their personal use for free. 
##  You can distribute the modified file for free without written consent from me but must have the credit of original author.
##  You can support this code on github.com/ACUnknown/QuickCredit

##-----DEFAULT PARAMETERS
#Also change the format of author in the code where needed.



authorName = "Your Name Here"
autoProDate=1 ## IF 1 , it will take File's date of modification in Header
autoDateFormat="%d-%m-%Y"
proDate = "12 February 2021"
Desc=["","","",""]

SaveFileDirectory="Final/"

StartFrom=1
EndTill=20

##-----ADVANCED
enable_output_footer=1 ###BETA currently doesnot support codes that take input
autoReadOutput=1
autoDetectInputTrigger="Scanner" ### If this phrase is found in source code, you will have to manually copy and paste the output.

#When AUTO is off and manually pasting Output, type this to stop pasting (escape sequence phrase) 
# Change this when it is stopping automatically
escSeq="xESCx" ##Not case sensitive

useExcelforDescription=1 ### You need xlrd >1.2
ExcelFilePath="Desc.xlsx"

if useExcelforDescription:
    import pandas as pd
    xlDesc=pd.read_excel(ExcelFilePath)
    # print(myDesc)
    Desc=xlDesc.values
    print(Desc)

i=StartFrom
import time,os,datetime

while(i<=EndTill):
    proNum=i
    filename = "myQ"+str(proNum)+".java"# Define the filename format here.


    with open(filename) as f:
        content = f.readlines()


    #Adding Header

    #Header Format
    if(autoProDate):
        proDate= (datetime.datetime.fromtimestamp(os.path.getmtime(filename=filename)).strftime(autoDateFormat) )

    proHeader = "/* @Author: " + authorName +"\n* @Date: " + proDate + "\n* Description: " + str(Desc[proNum-1]) + "\n*/\n\n\n"

    FinalStr = str(proHeader)


    #Adding Actual Code
    for line in content:
        FinalStr+=line

    #Adding Footer
    ##Turn on by setting "enable_output_footer=1" at top of code.
    if(enable_output_footer):
        import subprocess

        print("\n\nExecuting Java File Name: "+ filename+"\n\n")
        ###Compiling Java File
        os.system("javac myQ"+ str(proNum) + ".java")
        print(type(FinalStr))
        print("\n"+FinalStr)
        codeOutput=""        


        ####Automatically Detecting Input
        print("\nDetecting Custom Input = "+str(FinalStr.__contains__(autoDetectInputTrigger)))


        if(autoReadOutput==1 and FinalStr.__contains__(autoDetectInputTrigger)==0):
        ### No Inputs required            
            print("Automatically Taking Output.")
            codeOutput= subprocess.check_output(["java","myQ"+str(proNum)])

            FinalStr+="\n\n/* OUTPUT  automatically generated.\n"
            FinalStr+=str(codeOutput).replace('\\n', '\n').replace('\\t', '\t')
            FinalStr+="\n*/  //Generated by Github/ACUnknown/QuickCredit"
        else:
        ### User Input Required
            print("You may need to copy and paste output from below.\n")
            os.system("java myQ"+str(proNum))

            newLineOut=""
            while(newLineOut.lower()!=escSeq.lower()):
                newLineOut=input("\n\nPlease copy and paste the output of file number " + str(proNum) + " (type '" + escSeq + "' to complete pasting):")
                if(newLineOut.lower()!=escSeq.lower()):codeOutput+=newLineOut+"\n"
                    # print (codeOutput)
            FinalStr+="\n\n/* OUTPUT\n"
            FinalStr+=str(codeOutput).replace('\\n', '\n').replace('\\t', '\t')
            FinalStr+="\n*/"

        print("\nRan successfully")




    print("Final Output saved to file is:")




    print(FinalStr)


    ##Writing to file
    f = open(SaveFileDirectory+"myQ"+str(proNum)+"Final.java","w+")

    f.writelines(FinalStr)

    f.close()

    i=i+1
